from . import test_date_diff
from . import test_simple_field_boolean
from . import test_simple_field_number
from . import test_simple_field_selection
from . import test_simple_field_string
from . import test_related_field
from . import test_with_sudo
from . import test_current_user
from . import test_monetary_field
from . import test_check_find
